# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Mapbox GL Tests' do
  pod 'KIF', '~> 3.2.1'
  pod 'OCMock', '~> 3.1.2'
  pod 'OHHTTPStubs', '~> 4.0.2'
end

target 'Test Bundle' do
  pod 'KIF', '~> 3.2.1'
  pod 'OCMock', '~> 3.1.2'
  pod 'OHHTTPStubs', '~> 4.0.2'
end

